server:
  port: 8082

spring:
  application:
    name: dubbo-consumer1

dubbo:
  application:
    name: consumer1
    logger: slf4j
  registry:
    address: zookeeper://127.0.0.1:2181
    file: ${user.dir}/dubbo-cache/${spring.application.name}/dubbo.cache